### ISSUE TITLE
function string does not accept keyword argument error

### ISSUE THREAD

**Issue by rohith14** [JuliaLang/Microbenchmarks#21]
function parseintperf(t)
    local n, m
    for i=1:t
        n = rand(UInt32)
        s = string(n, base = 16)
        m = UInt32(parse(Int64,s, base = 16))
        @assert m == n
    end
    return n
end

@timeit parseintperf(1000) "parse_integers" "Integer parsing"

Error: function string does not accept keyword argument

Julia version: 0.6.4 (windows)

**Comment by Enet4** [comment]
This looks like a direct copy from [perf.jl, lines 18 to 27](https://github.com/JuliaLang/Microbenchmarks/blob/master/perf.jl#L18-L27). And I can reproduce this too. It appears that the issue mentioned [here](https://github.com/JuliaLang/Microbenchmarks/commit/c1284fd682ad9e4956d0fe442a9557f76b17ca63#commitcomment-28988608) is still in effect.

**Comment by StefanKarpinski** [comment]
Ok, nothing to be done on in repo.

**Comment by rohith14** [comment]
Thank you all.
