### ISSUE TITLE
Running Julia benchmarks in Single core mode

### ISSUE THREAD

**Issue by rohith14** [JuliaLang/Microbenchmarks#25]
Hi,

For running the benchmarks (reproducing the numbers on my end), how do I make sure Julia runs on single core?  For MATLAB, I see we use singleCompThread and is there something similar in Julia?

Thanks

**Comment by ChrisRackauckas** [comment]
The benchmarks are run in single, except maybe the matrix multiplication where every language is calling a multicore BLAS. In Julia, just change the number of BLAS threads to 1 if you want to change that test case, but you'd need to do that in each language as well.

**Comment by rohith14** [comment]
Thank you,, Chris
