### ISSUE TITLE
C++, C#, and VB

### ISSUE THREAD

**Issue by KayvanA** [JuliaLang/Microbenchmarks#35]
Hi guys,

I love your speed comparison benchmarks: https://julialang.org/benchmarks/
I find this information invaluable. All I need to know is gathered nicely in one graph! amazing.

Do you happen to know where C++, C#, and Visual Basic would fit in the graph? Do you expect C++ and C# be comparable to C? Do you expect VB to be comparable to Python, speed wise? Even if you haven't run the tests, I am curious to know where you _guess/feel_ they roughly fit in the comparison graph. That would be helpful to me in my decision for my work project.

Thank you,
Kayvan

**Comment by StefanKarpinski** [comment]
C++ will be the same as C (most compilers for one also compile the other). I'd guess that C# would be similar to Java, maybe a bit faster. VB will be somewhere between Python and R but will probably have issues with working with complex numbers and calling numerical libraries like BLAS, which will hurt it on some of the tests and might make it worse than anything else on here.

**Comment by KayvanA** [comment]
Thank you for your response, Stephen. Helpful!

If I may ask another question: Do you know if I develop my code in Julia, then would I be able to create a form for it easily, like in VB, or not?

I had used Julia for an iterative problem about a year ago or two. I used an editor at the time called Atom. I don't think I saw the Visual features there. Am I correct?

**Comment by StefanKarpinski** [comment]
> Do you know if I develop my code in Julia, then would I be able to create a form for it easily, like in VB, or not?

You mean like a web form? If so then yes, there are Julia web frameworks that can do that.

> I used an editor at the time called Atom.

Atom is the basis for the [Juno IDE](https://junolab.org) for Julia, which in turn is the basis for [JuliaPro](https://juliacomputing.com/products/juliapro).

>  I don't think I saw the Visual features there. Am I correct?

I'm not sure what that means...

**Comment by KayvanA** [comment]
By form something that can have buttons, menus, checkboxes, etc. I had made such a thing using VB before. With Julia/Julia Pro in Atom, I had created a simple numerical calculator which did not have any of these features (buttons, menus, etc.). I was wondering if I could develop my numerical code in Julia along with a form that has buttons, menus, checkboxes and so on.

Thanks!
Kayvan

**Comment by StefanKarpinski** [comment]
Best to ask on [discourse](https://discourse.julialang.org), but I think that sort of thing should be possible.

**Comment by KayvanA** [comment]
ok, thanks.
