### ISSUE TITLE
Why I run benchmark far fast than Official data

### ISSUE THREAD

**Issue by FlyHuss** [JuliaLang/Microbenchmarks#44]
c,recursion_fibonacci,0.000000. 
c,parse_integers,0.095689. 
c,userfunc_mandelbrot,0.048740. 
c,recursion_quicksort,0.254154. 
c,iteration_pi_sum,0.000000. 
c,matrix_statistics,5.580187. 
c,matrix_multiply,11.534214. 
c,print_to_file,12.454987. 

  
And the official c,iteration_pi_sum is 27second. Too much.
  
I run perf.c on mac bookpro 16(2019).

**Comment by ChrisRackauckas** [comment]
It looks like whatever compiler settings you ran it with completely elided the calculation at compile time and compiled to an analytical solution.

**Comment by FlyHuss** [comment]
> It looks like whatever compiler settings you ran it with completely elided the calculation at compile time and compiled to an analytical solution.

How can I do is correct?    

When I build perf.c with -O0:  
c,recursion_fibonacci,0.036743. 
c,recursion_fibonacci mean,0.040067. 
c,parse_integers,0.130520. 
c,userfunc_mandelbrot,0.104270. 
c,userfunc_mandelbrot,0.106560. 
c,recursion_quicksort,0.462055. 
c,iteration_pi_sum,11.065960. 
c,iteration_pi_sum mean,11.352777. 
c,matrix_statistics,7.568121. 
c,matrix_multiply,24.421930. 
c,print_to_file,12.791157. 
  
But official data is:  
c | iteration_pi_sum | 27.368069. 
c | matrix_multiply | 72.014809. 
c | matrix_statistics | 4.528999. 
c | parse_integers | 0.099249. 
c | print_to_file | 9.929895. 
c | recursion_fibonacci | 0.022732. 
c | recursion_quicksort | 0.258923. 
c | userfunc_mandelbrot | 0.076702. 

Why the gap is too big?

**Comment by johnfgibson** [comment]
The posted times are not that far off from the "official" data. E.g. for recursion_fibonacci you get 0.036743 versus the official 0.022732. That's a small difference considering you are running with -O0 and on likely different hardware. The data posted at julialang.org was run on an Intel(R) Core(TM) i7-3960X CPU @ 3.30GHz. What is your hardware?

You might try running with -O1 or -O2 and sorting the results the same way for easy comparison.

**Comment by FlyHuss** [comment]
> The posted times are not that far off from the "official" data. E.g. for recursion_fibonacci you get 0.036743 versus the official 0.022732. That's a small difference considering you are running with -O0 and on likely different hardware. The data posted at julialang.org was run on an Intel(R) Core(TM) i7-3960X CPU @ 3.30GHz. What is your hardware?
> 
> You might try running with -O1 or -O2 and sorting the results the same way for easy comparison.

My machine is : 6-Core Intel Core i7 2.6 GHZ ; 16 GB 2667 MHz DDR4 ;   
However, the "official" matrix_multiply and iteration_pi_sum times is too big.   
Is this normal?

**Comment by FlyHuss** [comment]
I have solved this problem.  
The reason is clang -O optimization that elided the function call in iteration_pi_sum.  

I have changed the test code in line 5 to print pi, And can output correct value：  
`

for (int i=0; i<NITER; ++i) {
        t = clock_now();
        pi = pisum();
        t = clock_now()-t;
        print_perf("iteration_pi_sum pi", pi);
        if (t < tmin) tmin = t;
    }
`

**Comment by acxz** [comment]
This is a known issue that the recent compilers are compiling away certain computations that we are timing altogether. Closing as a dup of #29 since this is specifically mentioning the pisum test on C.

**Comment by FlyHuss** [comment]
你好，你的邮件我已经收到了。祝开心！

**Comment by FlyHuss** [comment]
你好，你的邮件我已经收到了。祝开心！
