### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [JuliaLang/Microbenchmarks#63]
I suggest adding the topics `benchmark`, `microbenchmark`, `performance`, `language-comparison` in the About section at https://github.com/JuliaLang/Microbenchmarks.

**Comment by waldyrious** [comment]
Sorry to hijack this issue, but since this refers to changing the repository settings, I'd also suggest adding a link to https://julialang.org/benchmarks/ in the "website" field.

**Comment by acxz** [comment]
@ViralBShah sorry to ping you on this, seems like only members can add topics and website to the github repo. Do you mind tackling this real quick?

**Comment by ViralBShah** [comment]
Done.

**Comment by acxz** [comment]
Can we get the website page as well?

**Comment by ViralBShah** [comment]
Ah I didn't understand that earlier. Got it now.
