### ISSUE TITLE
Automatically sort table by geometric mean

### ISSUE THREAD

**Issue by waldyrious** [JuliaLang/Microbenchmarks#7]
According to [this comment](https://github.com/JuliaLang/julialang.github.com/pull/685#issuecomment-353437829), the entries of the [performance table](https://julialang.org/benchmarks/) are sorted by the geometric mean of their scores in each benchmark, but that is done manually. It would be nicer to have it happen automatically.

(x-ref #5)

**Comment by johnfgibson** [comment]
IMHO it would be best to do this by first rewriting `bin/collect.pl` and `bin/table.pl` to Julia, then adding the geometric mean calculation and sorting, as per suggestion by @StefanKarpinski a few months back.

**Comment by johnfgibson** [comment]
done, PR #13
