### ISSUE TITLE
Show "--" instead of "0.00" in the table for missing data points

### ISSUE THREAD

**Issue by waldyrious** [JuliaLang/Microbenchmarks#8]
From [this comment](https://github.com/JuliaLang/julialang.github.com/pull/685#issuecomment-353437829):

> The `--` in JavaScript's `print_to_file` is meant to indicate a missing value — JavaScript is sandboxed and can't print to a file, as far as I understand. The perl script as is generates 0.0 for this missing datapoint. I've been changing that to `--` manually. IMHO it'd be nice if the table.pl did this automatically, but I don't think it's a big deal either way.

**Comment by johnfgibson** [comment]
fixed by [PR #12](https://github.com/JuliaLang/Microbenchmarks/pull/12)
