### ISSUE TITLE
Drop perfutils.jl and use BenchmarkTools instead

### ISSUE THREAD

**Issue by waldyrious** [JuliaLang/Microbenchmarks#9]
From [this comment](https://github.com/JuliaLang/Microbenchmarks/pull/2#issuecomment-388958522):

> Ideally we should drop the perfutils.jl code and use BenchmarkTools instead. That can follow.

**Comment by StefanKarpinski** [comment]
We should, but that will create a bigger difference between how Julia code is measured and how other languages are measured, so perhaps not.

**Comment by waldyrious** [comment]
To be clear, I was just making sure scattered TODOs were being properly tracked. I have no strong opinion on this, so if there's agreement, this issue can be closed as far as I'm concerned.

**Comment by johnfgibson** [comment]
Good point. The perfutils.jl macros are simple, transparent, and easy to compare with timings in other languages. I'm good with keeping them and closing this issue.
